image: nixpkgs/nix-flakes:latest

stages:
  - build

variables:
  CACHIX_CACHE_NAME: midorishibukawa-ml
  PROJECT_NAME: twenty_fourty_eight
  
before_script:
  - nix profile install --accept-flake-config nixpkgs#cachix
  - cachix use "$CACHIX_CACHE_NAME"
  - export BISECT_FILE=${PWD}/cobertura
    
build:
  stage: build
  artifacts:
    paths:
      - twenty_fourty_eight
  script:
    - cachix watch-exec $CACHIX_CACHE_NAME -- nix build .#prd
    - cp result/bin/$PROJECT_NAME .

test:
  stage: build
  coverage: '/Coverage: \d*\/\d* \((.*)%\)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  script:
    - cachix watch-exec $CACHIX_CACHE_NAME -- nix develop -c make test
    - cachix watch-exec $CACHIX_CACHE_NAME -- nix develop -c bisect-ppx-report cobertura cobertura.xml

pages:
  stage: build
  artifacts:
    paths:
      - public
  script:
    - cachix watch-exec $CACHIX_CACHE_NAME -- nix develop -c make doc
    - mkdir -p public && cp -r _build/default/_doc/_html/* public